from enum import Enum

class tipoJobs(Enum):
    MAIL_QUERY_ALLEGATO_EXCEL = "MAIL_QUERY_ALLEGATO_EXCEL"
    MAIL_QUERY_ALLEGATO_EXCEL_OPENPYXL = "MAIL_QUERY_ALLEGATO_EXCEL_OPENPYXL"    
    MAIL_QUERY_ALLEGATO_EXCEL_OPENPYXL_MULTI_SHEET = "MAIL_QUERY_ALLEGATO_EXCEL_OPENPYXL_MULTI_SHEET"    
    MAIL_QUERY_ALLEGATO_GRAFICI_CA_CSV_GIORNALIERO = "MAIL_QUERY_ALLEGATO_GRAFICI_CA_CSV_GIORNALIERO"
    MAIL_QUERY_ALLEGATO_GRAFICI_CA_CSV_MENSILE = "MAIL_QUERY_ALLEGATO_GRAFICI_CA_CSV_MENSILE"
    PDF_QUERY_FS_CSV = "PDF_QUERY_FS_CSV"
    MAIL_QUERY_BODY_HTML = "MAIL_QUERY_BODY_HTML"
    MAIL_QUERY_BODY_HTML_WP = "MAIL_QUERY_BODY_HTML_WP"    
  
